### ISSUE TITLE
No Pod

### ISSUE THREAD

**Issue by nileshpol18** [BrammanandSoni/BRImagePicker#2]
There is no way to install using pod?

**Comment by BrammanandSoni** [comment]
I will add it to cocoa pods today or tomorrow. Once i will add, i will
reply to this mail.

Thanks,
Brammanand Soni

**Comment by nileshpol18** [comment]
Sure, @BrammanandSoni , will look forward and hoping that it'll be available today.
Thanks

**Comment by nileshpol18** [comment]
@BrammanandSoni , can you please add cocoa pods asap? Thanks.

**Comment by BrammanandSoni** [comment]
Hi Nilesh,

```
 Sorry for the delay. I was little busy.
```

Now BRImagePicker is available on cocoapods.
Here is the link:

https://github.com/BrammanandSoni/BRImagePickerPod

I'd love to have feedback from you.

Thanks,
Brammanand

**Comment by nileshpol18** [comment]
Hi Brammanand,

Thanks for uploading the pod. I installed from terminal and following is the message I got on terminal: 
    
    [!] Unable to find a specification for `BRImagePicker`

I am sure that I have followed the correct process for installation. Following is the snapshot of my pod file:

    source 'https://github.com/CocoaPods/Specs.git'

    platform :ios, “9.0”

    use_frameworks!

    target "DemoPicker" do

    pod 'BRImagePicker'
  
    end

I even tried   pod 'BRImagePicker'

**Comment by nileshpol18** [comment]
Hi @BrammanandSoni ,

Thanks a lot for pod. I have installed it and works fine

**Comment by BrammanandSoni** [comment]
Great.

Thanks,
Brammanand
