### ISSUE TITLE
Getting crashed in iOS 10

### ISSUE THREAD

**Issue by nileshpol18** [BrammanandSoni/BRImagePicker#4]
Working fine with iOS previous versions. However, getting crashed for iOS 10 while opening the picker.

Also working fine in iOS 10 on simulator but getting crashed on device with iOS 10

Debugger: terminated due to memory issue

**Comment by nishanth9493** [comment]
any solution for the above??
facing the same issue

**Comment by BrammanandSoni** [comment]
Hi Nilesh,
     I have fixed the issue on iOS 10. you can check now.
Sorry for the delay.

**Comment by sainiarpit38** [comment]
working fine on simulator but getting crashed on device if Photo album Have image more then 40.

Debugger: terminated due to memory issue

Any Solution ??
